/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ForgotPassword11`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPassword21`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPassword31`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted11`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted21`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted31`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted41`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted51`; params?: Router.UnknownInputParams; } | { pathname: `/LoginToYourAccount11`; params?: Router.UnknownInputParams; } | { pathname: `/LoginToYourAccount21`; params?: Router.UnknownInputParams; } | { pathname: `/LoginToYourAccount31`; params?: Router.UnknownInputParams; } | { pathname: `/OnboardingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SplashScreen1`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/HomeIndicator`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ForgotPassword11`; params?: Router.UnknownOutputParams; } | { pathname: `/ForgotPassword21`; params?: Router.UnknownOutputParams; } | { pathname: `/ForgotPassword31`; params?: Router.UnknownOutputParams; } | { pathname: `/GetStarted11`; params?: Router.UnknownOutputParams; } | { pathname: `/GetStarted21`; params?: Router.UnknownOutputParams; } | { pathname: `/GetStarted31`; params?: Router.UnknownOutputParams; } | { pathname: `/GetStarted41`; params?: Router.UnknownOutputParams; } | { pathname: `/GetStarted51`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginToYourAccount11`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginToYourAccount21`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginToYourAccount31`; params?: Router.UnknownOutputParams; } | { pathname: `/OnboardingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SplashScreen1`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/HomeIndicator`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/ForgotPassword11${`?${string}` | `#${string}` | ''}` | `/ForgotPassword21${`?${string}` | `#${string}` | ''}` | `/ForgotPassword31${`?${string}` | `#${string}` | ''}` | `/GetStarted11${`?${string}` | `#${string}` | ''}` | `/GetStarted21${`?${string}` | `#${string}` | ''}` | `/GetStarted31${`?${string}` | `#${string}` | ''}` | `/GetStarted41${`?${string}` | `#${string}` | ''}` | `/GetStarted51${`?${string}` | `#${string}` | ''}` | `/LoginToYourAccount11${`?${string}` | `#${string}` | ''}` | `/LoginToYourAccount21${`?${string}` | `#${string}` | ''}` | `/LoginToYourAccount31${`?${string}` | `#${string}` | ''}` | `/OnboardingScreen${`?${string}` | `#${string}` | ''}` | `/SplashScreen1${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/HomeIndicator${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ForgotPassword11`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPassword21`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPassword31`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted11`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted21`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted31`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted41`; params?: Router.UnknownInputParams; } | { pathname: `/GetStarted51`; params?: Router.UnknownInputParams; } | { pathname: `/LoginToYourAccount11`; params?: Router.UnknownInputParams; } | { pathname: `/LoginToYourAccount21`; params?: Router.UnknownInputParams; } | { pathname: `/LoginToYourAccount31`; params?: Router.UnknownInputParams; } | { pathname: `/OnboardingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SplashScreen1`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/HomeIndicator`; params?: Router.UnknownInputParams; };
    }
  }
}
